// This is only here for Webstorm to recognize the project as using Tailwind CSS
export default {
  theme: {
    extend: {
      colors: {
        base: 'var(--color-base)',
        gray: {
          1: 'var(--color-gray-1)',
          2: 'var(--color-gray-2)',
          3: 'var(--color-gray-3)',
          4: 'var(--color-gray-4)',
          5: 'var(--color-gray-5)',
          6: 'var(--color-gray-6)',
          7: 'var(--color-gray-7)',
          8: 'var(--color-gray-8)',
          9: 'var(--color-gray-9)',
          10: 'var(--color-gray-10)',
          11: 'var(--color-gray-11)',
          12: 'var(--color-gray-12)',
          a1: 'var(--color-gray-a1)',
          a2: 'var(--color-gray-a2)',
          a3: 'var(--color-gray-a3)',
          a4: 'var(--color-gray-a4)',
          a5: 'var(--color-gray-a5)',
          a6: 'var(--color-gray-a6)',
          a7: 'var(--color-gray-a7)',
          a8: 'var(--color-gray-a8)',
          a9: 'var(--color-gray-a9)',
          a10: 'var(--color-gray-a10)',
          a11: 'var(--color-gray-a11)',
          a12: 'var(--color-gray-a12)',
        },
        primary: {
          1: 'var(--color-primary-1)',
          2: 'var(--color-primary-2)',
          3: 'var(--color-primary-3)',
          4: 'var(--color-primary-4)',
          5: 'var(--color-primary-5)',
          6: 'var(--color-primary-6)',
          7: 'var(--color-primary-7)',
          8: 'var(--color-primary-8)',
          9: 'var(--color-primary-9)',
          10: 'var(--color-primary-10)',
          11: 'var(--color-primary-11)',
          12: 'var(--color-primary-12)',
          a1: 'var(--color-primary-a1)',
          a2: 'var(--color-primary-a2)',
          a3: 'var(--color-primary-a3)',
          a4: 'var(--color-primary-a4)',
          a5: 'var(--color-primary-a5)',
          a6: 'var(--color-primary-a6)',
          a7: 'var(--color-primary-a7)',
          a8: 'var(--color-primary-a8)',
          a9: 'var(--color-primary-a9)',
          a10: 'var(--color-primary-a10)',
          a11: 'var(--color-primary-a11)',
          a12: 'var(--color-primary-a12)',
        },
        white: {
          a1: 'var(--color-white-a1)',
          a2: 'var(--color-white-a2)',
          a3: 'var(--color-white-a3)',
          a4: 'var(--color-white-a4)',
          a5: 'var(--color-white-a5)',
          a6: 'var(--color-white-a6)',
          a7: 'var(--color-white-a7)',
          a8: 'var(--color-white-a8)',
          a9: 'var(--color-white-a9)',
          a10: 'var(--color-white-a10)',
          a11: 'var(--color-white-a11)',
          a12: 'var(--color-white-a12)',
        },
        black: {
          a1: 'var(--color-black-a1)',
          a2: 'var(--color-black-a2)',
          a3: 'var(--color-black-a3)',
          a4: 'var(--color-black-a4)',
          a5: 'var(--color-black-a5)',
          a6: 'var(--color-black-a6)',
          a7: 'var(--color-black-a7)',
          a8: 'var(--color-black-a8)',
          a9: 'var(--color-black-a9)',
          a10: 'var(--color-black-a10)',
          a11: 'var(--color-black-a11)',
          a12: 'var(--color-black-a12)',
        }
      }
    }
  },
  plugins: []
}
